// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Jn144LOcdqcew8Z674jR2mqX4DSa1Sw',
    appId: '1:1033106870447:web:f303e2fe175242794c845a',
    messagingSenderId: '1033106870447',
    projectId: 'tiktok-app-8fd3e',
    authDomain: 'tiktok-app-8fd3e.firebaseapp.com',
    storageBucket: 'tiktok-app-8fd3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE8pJNKqbegpwTc9Bv8DiogeoqpGEQ4qE',
    appId: '1:1033106870447:android:be9792f554da69f94c845a',
    messagingSenderId: '1033106870447',
    projectId: 'tiktok-app-8fd3e',
    storageBucket: 'tiktok-app-8fd3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJUgCgbh9H6C9Fyp8Y1WdHoOwge5kKzg',
    appId: '1:1033106870447:ios:787cccfdce6019b34c845a',
    messagingSenderId: '1033106870447',
    projectId: 'tiktok-app-8fd3e',
    storageBucket: 'tiktok-app-8fd3e.firebasestorage.app',
    iosBundleId: 'com.example.tiktokFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJUgCgbh9H6C9Fyp8Y1WdHoOwge5kKzg',
    appId: '1:1033106870447:ios:787cccfdce6019b34c845a',
    messagingSenderId: '1033106870447',
    projectId: 'tiktok-app-8fd3e',
    storageBucket: 'tiktok-app-8fd3e.firebasestorage.app',
    iosBundleId: 'com.example.tiktokFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Jn144LOcdqcew8Z674jR2mqX4DSa1Sw',
    appId: '1:1033106870447:web:b11b85f568e3be854c845a',
    messagingSenderId: '1033106870447',
    projectId: 'tiktok-app-8fd3e',
    authDomain: 'tiktok-app-8fd3e.firebaseapp.com',
    storageBucket: 'tiktok-app-8fd3e.firebasestorage.app',
  );
}
